name: Check lint

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  check-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Install dependencies
        run: yarn

      - name: Check the linting
        run: yarn check-lint
