name: Performance

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-unit:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: yarn